on: [push]

jobs:
  test_job:
    runs-on: ${{ matrix.os }}
    name: Test installation on ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - id: install-version
        uses: diku-dk/install-mlkit@HEAD
        with:
          version: '4.7.17'
      - id: install-no-version
        uses: diku-dk/install-mlkit@HEAD
      - id: install-latest
        uses: diku-dk/install-mlkit@HEAD
        with:
          version: 'latest'

      - run: mlkit test.mlb
